### ISSUE TITLE
Package grommet does not exists.

### ISSUE THREAD

**Issue by nuty** [RenaissanceBug/racket-jwt#4]
Package grommet does not exists. can you use module "sha"?

**Comment by RenaissanceBug** [comment]
Thanks for tipping me off. I'm looking into it now.

The grommet package's SHA HMAC function was a ```String String -> Bytes``` function, but the ```sha``` package's equivalent is ```Bytes Bytes -> Bytes```. I may make this a backwards-incompatible change and fix the documentation accordingly — or, more likely, I may require ```SigningFunction```s to take either strings or byte strings, and provide a parameter specifying the conversion function (defaulting to ```string->bytes/utf-8```).

I'll keep you posted.

**Comment by nuty** [comment]
@RenaissanceBug thanks your reply， second way you said is good solution  i think.

**Comment by RenaissanceBug** [comment]
Fixed by commit 94e4bf39d126797075eeb5eb2e2a7e1a397e22c2 and the following two commits.

Let me know of any further issues. Thanks for bringing this one up.
